### ISSUE TITLE
/current redirects to the prod app

### ISSUE THREAD

**Issue by LindsayYoung** [fecgov/fec-eregs#364]
This is an infrastructure task
- [ ] set up differently on cloud.gov
- [ ] dependent upon deploying eRegs

I think the regulations site is creating redirects for /current but this is happening in the app and it is pointing to the app and not the proxied address.

We don't need redirects for eregs, so we might want to handle this with cloud.gov's built in stuff and not pother with the proxy. Or we can look at changing the regulations-site parser.

I think this is the code giving us an issue:
https://github.com/eregs/regulations-site/blob/d9223d07d92e54926c5bbcffee1690581d715d83/regulations/urls.py#L87

**Comment by dorothyyeager** [comment]
@rhoughfec and I took a look at the issues and this will most likely require the assistance of a back-end person.

**Comment by LindsayYoung** [comment]
Documentation on cf routes:

- https://cloud.gov/docs/apps/custom-domains/#how-domains-and-routes-work-in-cloud-gov
- https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html

Basically, we will want to change the route so regulations don't use the proxy. This simplifies things architecturally and will get the redirects for /latest working correctly. (Once we have fewer redirects in use we can do the same thing for the cms as well and just handle the redirects in wagtail. We will still need the proxy for s3 bucket naming.) 

### The routes need to be changed from :

space | host | domain | apps 
-- | -- | -- | --
dev  |  fec-dev-eregs    |    app.cloud.gov  | eregs
stage  |  fec-stage-eregs    |    app.cloud.gov  | eregs
prod  |  fec-prod-eregs  |   app.cloud.gov   |  eregs


### Change route to:

space | host | domain | apps 
-- | -- | -- | --
dev  |  fec-dev-proxy/regulations | app.cloud.gov | eregs
stage |  fec-stage-proxy/regulations | app.cloud.gov |  eregs
prod |   | www.fec.gov/regulations  |  eregs

- [ ] double check we can do a route in the domain, if not we can take the same approach in prod, using the fec-prod-proxy/regulations host and app.cloud.gov domain

Go ahead and update the architecture diagram so that it is clear that eregs doesn't use the proxy after this is done.

**Comment by AmyKort** [comment]
Is this issue being addressed already as part of the work you are doing now, @pkfec ?

**Comment by pkfec** [comment]
rerouting the eregs app to proxy is already taken care of. we can close this issue.
