### ISSUE TITLE
Optimize loading of regulations

### ISSUE THREAD

**Issue by vrajmohan** [fecgov/fec-eregs#369]
The task is to automate the parsing and loading of regulations. Work on this was already started and partially completed by @anthonygarvan in #349. We should complete this work.

**Comment by vrajmohan** [comment]
This came up during our loading workshop. I recommend taking this up in 4.5.

**Comment by AmyKort** [comment]
Great! Thanks for flagging. I'm tagging @pkfec and @lbeaufort  for visibility, but we'll make assignments during sprint planning.

**Comment by vrajmohan** [comment]
The work for this was completed in #349 .
