### ISSUE TITLE
Reload regulations for 2018

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-eregs#371]
There were three new Federal Register notices with rules to be included in the 2018 11 CFR - https://www.fec.gov/legal-resources/regulations/

Because of the CFR changes, I believe we'll need to reload the regulations, ideally on or around Jan 1. CFR 11 gets published Jan 1, and the regulations need to be re-parsed and re-loaded into eregs.

My notes from @vraj’s overview on how to re-load the regs: https://docs.google.com/document/d/1nNPusnjKjl0Nb7kQYPQrhQ8o7_8i83HpUkqRwsebKJ4/edit

**Comment by vrajmohan** [comment]
Is this a duplicate of #387?

**Comment by lbeaufort** [comment]
Yes, thanks! My timing was off (regs need to be reloaded around March when they're published [here](https://www.govinfo.gov/bulkdata/ECFR/title-11). Closing this issue.
