### ISSUE TITLE
Eregs to do

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-eregs#374]
Add parser instructions

`pip install regparser`

Need to run p

parser has it's own version of Django, and api eregs has separate Django, it's trying to read the same settings file so we need to make a separate virtual environment just for the parser itself.

To run parser:

Need to `unset DATABASE_URL` 

@cmc333333 to give instructions on what command to run eregs parser on entire title 11.

**Comment by AmyKort** [comment]
resolved!
