### ISSUE TITLE
Transfer fec-eregs GitHub repo to FEC

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-eregs#379]
- [x] [fec-eregs](https://github.com/18F/fec-eregs): the FEC's new Code of Federal Regulations explorer
    - [x]  set up circle
    - [x] set up Slack web hooks
    - [x] set up gemnasium alerts

**Comment by AmyKort** [comment]
@ccostino @LindsayYoung

**Comment by pkfec** [comment]
fec-eregs repo is transferred to **fecgov** org. kicked-off  the first eregs build on circleci.

just like pattern-library, will have to set up the gemnasium alerts on eregs repo. Will work with 
@patphongs , @lbeaufort and @lbeaufort on this.

**Comment by LindsayYoung** [comment]
Thanks @pkfec marked this on the master list too https://github.com/fecgov/fec-transition/issues/155
