### ISSUE TITLE
Update cloud.gov manifest setup in e-regs

### ISSUE THREAD

**Issue by ccostino** [fecgov/fec-eregs#380]
[Manifest inheritance](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#minimize-duplication) has been deprecated in Cloud Foundry in favor of another type of setup using something called a YAML anchor.

Instead of inheriting manifest files from each other, you declare a defaults section in your manifest file that other sections then reference.  Unfortunately what this means for us is increased duplication since we have separate manifests for each space, but we want to make sure this is accounted for before the manifest inheritance is just shut off completely on us (this change happened about a year ago).

To update the API we'll have to do the following:

* [x] Copy everything in the base manifest file to their respective manifest files for each space
* [x] Make sure each manifest file for each space still works as expected

**Comment by lbeaufort** [comment]
@ccostino it looks like the `host` attribute has been replaced with `routes` as well. I'll incorporate that into my changes

https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated
The following route component attributes have been deprecated:
domain
domains
host
hosts
no-hostname

**Comment by patphongs** [comment]
This work has been completed in #384. Just need to monitor stage and prod deploys to make sure they deploy correctly. But for all intents and purposes, this issue can be closed unless we have a problem deploying to the other spaces.

**Comment by ccostino** [comment]
🎉 thank you, @lbeaufort and @patphongs!  So far so good, everything looks okay to me and great catch on the other deprecated piece. :-)
