### ISSUE TITLE
Arrange the penalty table contents on chart a and chart b in a numeric order

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-eregs#391]
On Part 111/111.43, the penalties table contents(Chart a and Chart b) are not displaying in a numeric order. Fix the table which sorts and displays the amounts in a numeric order.

Here is the Part#
https://fec-dev-proxy.app.cloud.gov/regulations/111-43/2018-annual-111#111-43

Screen shots of Chart a and Chart b:
<img width="783" alt="screen shot 2018-04-13 at 12 51 44 pm" src="https://user-images.githubusercontent.com/11650355/38747715-bdede770-3f19-11e8-82ff-e8d4f62f432d.png">
<img width="789" alt="screen shot 2018-04-13 at 12 51 57 pm" src="https://user-images.githubusercontent.com/11650355/38747722-c3b235f8-3f19-11e8-9b04-18258058ccc1.png">

**Comment by pkfec** [comment]
@AmyKort @dorothyyeager 
fec-eregs repo has default char/string sort enabled on tables. So above charts are sorted by string which is why they are out of order. Do we know if there are any other charts/ tables in other parts of regulations? 

cc @vrajmohan

**Comment by dorothyyeager** [comment]
There's a chart at https://www.fec.gov/regulations/4-9/2018-annual-4#4-9-c-4 and there's two charts in https://www.fec.gov/regulations/5-6/2018-annual-5#5-6. That's it as far as I know. @pkfec  @vrajmohan

**Comment by pkfec** [comment]
@AmyKort @dorothyyeager 

The Charts listed above in Part 4 and Part 5 are not embedded in a table. 
It appears that the sorting logic on fec-eregs should be refactored to sort based of integer and not string. Can you have some one from the front end team look into this?

cc @vrajmohan

**Comment by AmyKort** [comment]
https://github.com/fecgov/fec-eregs/issues/402

**Comment by pkfec** [comment]
After discussing the issue with @AmyKort  and @vrajmohan , we all agreed to remove the default headers sort on above chars. And rearrange the table contents in ascending order.

**Comment by AmyKort** [comment]
Great! I'll move this issue to 5.6.

**Comment by JonellaCulmer** [comment]
@pkfec @AmyKort Just spotted this dropped issue from 5.5/5.6. Is this still valuable/relevant work that needs to be considered for upcoming work? Or can we close this in favor of other issues?

**Comment by AmyKort** [comment]
@JonellaCulmer can we hang into this blocked issue for a while? Thanks!

**Comment by JonellaCulmer** [comment]
@AmyKort @pkfec Do we need still need to hang on to this issue?

**Comment by AmyKort** [comment]
Let's close this. If it is causing actual problems for users, it will resurface.
