### ISSUE TITLE
Change the Title of 2.2(b) to be Commissioner or Member

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-eregs#392]
https://fec-dev-proxy.app.cloud.gov/regulations/2-2/2018-annual-2#2-2

Title says "Commissioner" but should say "Commissioner or Member" (Member part is there, but needs to move to the title.)

<img width="755" alt="screen shot 2018-04-13 at 12 59 31 pm" src="https://user-images.githubusercontent.com/11650355/38747960-928f5ad6-3f1a-11e8-96a3-a2cf743f3d23.png">

**Comment by pkfec** [comment]
Here is the screenshot of title 2.2(b) after it is fixed:


<img width="882" alt="screen shot 2018-04-26 at 2 21 18 pm" src="https://user-images.githubusercontent.com/11650355/39324316-316a65a0-495d-11e8-96c1-d283060edf49.png">

Due to firewall blocking the IP addresses on MAC, we cannot test  on my local workspace.
I am going to load the latest Part2 reg on **dev**.

cc @AmyKort @dorothyyeager

**Comment by AmyKort** [comment]
Looks good to me, but @dorothyyeager should take a look too.

**Comment by dorothyyeager** [comment]
It looks good in your screencap. In dev I am still seeing the way it was before it was fixed.

**Comment by pkfec** [comment]
The fix is not deployed to **dev** yet.   I will let you know when the Part 2 reg is loaded and ready for you guys to test in **dev** environment.

Thank you @AmyKort and @dorothyyeager for looking into this.

**Comment by pkfec** [comment]
@AmyKort @dorothyyeager 
I have loaded the Part 2 reg on  **dev** environment. Please test.

Here is the screen shot from **dev** environment:

<img width="870" alt="screen shot 2018-04-26 at 9 38 44 pm" src="https://user-images.githubusercontent.com/11650355/39340109-466eb0ea-499a-11e8-80b7-21aabb420449.png">

**Comment by dorothyyeager** [comment]
Looks perfect to me! @pkfec Thanks!

**Comment by dorothyyeager** [comment]
Just took a look at both and Part 2 is looking good. Thanks!

**Comment by pkfec** [comment]
I will close this issue.Thank you @dorothyyeager.
