### ISSUE TITLE
Update Elasticsearch to version 5.6 or remove service if it's not being used - eregs

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-eregs#396]
cloud.gov now has support for Elasticsearch version 5.6 more info [here](https://cloud.gov/docs/services/elasticsearch56/), which may improve some of the performance issues we've been having with our current version (2.4).

Also, cloud.gov may end support for 2.4 in the medium-term future.

See openFEC work: https://github.com/fecgov/openFEC/issues/2921
Thank you @fec-jli for flagging this!

**Completion criteria:**
- [x] Remove Elasticsearch 2.4 services from dev instance and test to make sure things still work
   - cf delete-service fec-api-search
   - cf unbind-service eregs fec-eregs-search
   - cf delete-service fec-eregs-search
- [x] Remove from stage and test there
   - `cf unbind-service eregs fec-eregs-search`
   -  `cf delete-service fec-eregs-search`
   -  fec-api-search : This  ES24 service is already deleted from `stage` space .No action required

- [x] Remove from production and test again
   - `cf unbind-service eregs fec-eregs-search`
   -  `cf delete-service fec-eregs-search`
   -  fec-api-search  :  This ES24 service is already deleted from `prod` space .No action required

**Comment by pkfec** [comment]
By looking at the **fec-eregs** repo requirements.txt we have  **pyelasticsearch==1.4** package. eregs repo doesn't  have a direct reference to latest Elastic Search library.

I do not think this repo needs any updates.

**Comment by lbeaufort** [comment]
@pkfec thanks for taking a look! If you look at `cf services` it looks like eregs has an instance of elasticsearch set up that's version 2.4... I'm not sure how/if they work together and whether it matters if eregs is using Elasticsearch 2.4 - @vrajmohan thoughts?

**Comment by pkfec** [comment]
i think its a matter of creating a new ES cloud service **elasticsearch56** in cloud and binding it the *fec-eregs-search*.

cc @vrajmohan and @lbeaufort

**Comment by vrajmohan** [comment]
@pkfec is correct, but I am curious to see if the service is needed at all as we use `fec-api-search` for searching regulations as well.

**Comment by AmyKort** [comment]
What is the status if this issue?

**Comment by lbeaufort** [comment]
@AmyKort This issue hasn't been assigned or given a milestone.

**Comment by lbeaufort** [comment]
@AmyKort I updated the title to reflect the additional work - I would want to do careful research to make sure it could get removed.

**Comment by pkfec** [comment]
Annual regulations are saved in `AWS shared database` instance in the cloud. `eregs` app do not consume the elasticsearch service at all. I have deleted below **two es24** services from `dev` space that are no longer needed or accessed from our apps anywhere.

1. fec-api-search
2. fec-eregs-search

**Comment by pkfec** [comment]
@AmyKort @dorothyyeager i have updated the completion criteria a little bit.

**Comment by AmyKort** [comment]
Awesome! Thanks @pkfec !

**Comment by dorothyyeager** [comment]
Yes, thanks!

**Comment by pkfec** [comment]
Deleted the unused ES24 service `fec-eregs-search` from `Stage` space today. On `Prod`space, i will delete the `fec-eregs-search` after the 7.4 release( scheduled on 11/6/2018).

**Comment by pkfec** [comment]
I have deleted the unused `fec-eregs-search` ES24 service from `prod` space after the 7.4 release today.
 Closing this issue.
