### ISSUE TITLE
Bug: Glossary link does not work on e-regs page

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-eregs#407]
@dorothyyeager commented on [Tue Jun 19 2018](https://github.com/fecgov/fec-cms/issues/2105)

Problem:
The link at the top of the page to open the glossary on the e-regs pages (https://www.fec.gov/regulations) has gone dead.

Completion criteria:
- [ ]  Fix the link to the glossary at the top of the e-regs pages.

**Comment by lbeaufort** [comment]
https://github.com/fecgov/fec-eregs/blob/develop/fec_eregs/templates/regulations/main-header.html#L13

**Comment by patphongs** [comment]
Combined with #409
