### ISSUE TITLE
Update header on eregs to be consistent with main site/add glossary

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-eregs#409]
- About menu is missing
- Still has the "old style" menus
- Look for other inconsistencies
- Fix the glossary issue. Closed #407 so that this can be combined.

![image](https://user-images.githubusercontent.com/31420082/41911294-43bb6b04-791a-11e8-8f56-886002d7e8dc.png)

**Comment by JonellaCulmer** [comment]
PR has been merged, so closing this issue.
