### ISSUE TITLE
[Med] Snyk: Information Exposure requests module(same as cms issue) [01/06/19]

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-eregs#422]
Issue description: [https://app.snyk.io/vuln/SNYK-PYTHON-REQUESTS-72435](https://app.snyk.io/vuln/SNYK-PYTHON-REQUESTS-72435)

**Remediation**
Upgrade request to version 2.20 or higher.

Same issue as cms: [https://github.com/fecgov/fec-cms/issues/2456](https://github.com/fecgov/fec-cms/issues/2456)

**Comment by qqss88** [comment]
it is a little confusing: 
not sure fec-eregs is even using this 'requests' package.

**Comment by fec-jli** [comment]
@qqss88  check this : https://app.snyk.io/org/fecgov/project/5e01de94-91bc-43d8-90b1-8843384b4b26
you will see MEDIUM SEVERITY.

**Comment by qqss88** [comment]
@fec-jli I understand that. what i don't understand is that it seems like we are NOT using this module in our code base, why do we keep it in our package list in the first place?

**Comment by pkfec** [comment]
Upgraded the `requests` package to the latest version 2.21.0 in requirements.txt file
https://pypi.org/project/requests/#history. I 

I will create a new ticket to triage the regparser issue that we came across while parsing 2018 regulations on our local env.
