### ISSUE TITLE
Update manifests to specify cflinuxfs2 stack

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-eregs#431]
We need to Update manifests to specify cflinuxfs2 stack before release
- [x] add stack variable to manifest files
- [x] deploy and test the eregs app with cflinuxfs2  
- [x] update the stack to cflinuxfs3
- [x] deploy and test eregs app with cflinuxfs3
- [ ] cut a release branch for eregs

**Comment by pkfec** [comment]
I have updated the comments to include the deploy and test with the latest buildpack `cflinuxfs3` to make that eregs app works OK after the buildpack upgrade.
