### ISSUE TITLE
[Med] Snyk: Race Condition (due 5/20/19)

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/fec-eregs#435]
**Vulnerable module:** webargs
Introduced through: webargs@0.18.0 and flask-apispec@0.7.0

**Detailed paths:**
Introduced through: project@0.0.0 › webargs@0.18.0
Introduced through: project@0.0.0 › flask-apispec@0.7.0 › webargs@0.18.0

**Remediation:**
Upgrade webargs to version 5.1.3 or higher.

**Comment by jason-upchurch** [comment]
Current description/detailed path in the Snyk log:

**Race Condition**
Vulnerable module: webargs
- Introduced through: regcore@4.2.0 and webargs@1.8.1

**Detailed paths**
- Introduced through: project@0.0.0 › regcore@4.2.0 › webargs@1.8.1
- Introduced through: project@0.0.0 › webargs@1.8.1
