### ISSUE TITLE
Denial of Service (DoS) --MEDIUM SEVERITY (from check logs)

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-eregs#437]
package.json 1 medium
Denial of Service (DoS) --MEDIUM SEVERITY
Vulnerable module: mem
Introduced through: npm@6.8.0
[https://app.snyk.io/vuln/npm:mem:20180117](https://app.snyk.io/vuln/npm:mem:20180117)

**Comment by jason-upchurch** [comment]
Snyk is no longer flagging this as an issue. Closing ticket.
