### ISSUE TITLE
[Med] Snyk: Prototype Pollution (due 6/10/19)

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/fec-eregs#439]
https://app.snyk.io/vuln/SNYK-JS-JQUERY-174006

**Overview**
jquery is a JavaScript library. It makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much simpler with an easy-to-use API that works across a multitude of browsers.

Affected versions of this package are vulnerable to Prototype Pollution. The extend function can be tricked into modifying the prototype of Object when the attacker controls part of the structure passed to this function. This can let an attacker add or modify an existing property that will then exist on all objects.

Vulnerable module: jquery
Introduced through: jquery@3.2.1

**Remediation**
~~A fix was pushed into the master branch but not yet published.~~
Upgrade jquery to version 3.4.0 or higher. [edit: 6/17/19]

**Comment by jason-upchurch** [comment]
Ran CLI `snyk test --file=package.json` and saw no warning. Opened issue with snyk: https://github.com/snyk/snyk/issues/524
