### ISSUE TITLE
[HIGH] CRLF injection fix by May 24, 2019

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-eregs#442]
**CRLF injection**
Vulnerable module: urllib3
- Introduced through: requests-toolbelt@0.8.0, regulations@8.4.2 and others

**Detailed paths**
- Introduced through: project@0.0.0 › requests-toolbelt@0.8.0 › requests@2.21.0 › urllib3@1.25
- Introduced through: project@0.0.0 › regulations@8.4.2 › requests@2.21.0 › urllib3@1.25
- Introduced through: project@0.0.0 › pyelasticsearch@1.4 › elasticsearch@1.9.0 › urllib3@1.25
- Introduced through: project@0.0.0 › requests@2.21.0 › urllib3@1.25
- Introduced through: project@0.0.0 › pyelasticsearch@1.4 › urllib3@1.25

**Overview**
urllib3 is an HTTP library with thread-safe connection pooling, file post, and more.

Affected versions of this package are vulnerable to CRLF injection. Attacker who has the control of the requesting address parameter, could manipulate an HTTP header and attack an internal service.

**Remediation**
A fix was pushed into the master branch but not yet published.

**Comment by fec-jli** [comment]
1)check requirements.txt,  found requests==2.21.0 
2)check snyk, CRLF injection Vulnerable no longer show.
[https://app.snyk.io/org/fecgov/project/5e01de94-91bc-43d8-90b1-8843384b4b26](https://app.snyk.io/org/fecgov/project/5e01de94-91bc-43d8-90b1-8843384b4b26)
3) so close this issue.
