### ISSUE TITLE
Reload e-regs for 2019 11 CFR and rules published since

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-eregs#443]
**What we are after**
Making sure the e-regs are up to date for users.

**Background**
In the past few months, there have been some reg changes, so it's time to reload the e-regs. 

Also, the xml file for the 2019 11 CFR is now available: https://www.govinfo.gov/content/pkg/CFR-2019-title11-vol1/xml/CFR-2019-title11-vol1.xml

**To do**
- [ ] Reload the regulations.
- [ ] Test in dev, stage and prod

**Comment by dorothyyeager** [comment]
In case it's needed, here's the link to the point of entry rules: https://sers.fec.gov/fosers/showpdf.htm?docid=402849

**Comment by fec-jli** [comment]
We try to load 2019 eregs data to 'dev' space. for some reasons, it loads both 2018 and 2019 data into `dev` eregs-db. we need figure out how to handle this issue. 
1)remove the 2018 data from `dev` eregs db
0r 2) modify our regulation search to get rid of 2018 data.

**Comment by dorothyyeager** [comment]
The duplicate 2018 data was removed. Thank you @fec-jli and @qqss88 for your work on this.

Just tested the eregs in data. All of the changes made to 11 CFR that were included in the 2019 edition are showing up properly.

The biggest issue I see (and it's in the current version on fec.gov too) is that links to the old GPO website need to be updated. They were pointing to GPO's old API at fdsys.gov but need to update to govinfo.gov:

- Statute links for 52 USC are pointing to https://api.fdsys.gov/... but need to point to the pages linked at https://www.govinfo.gov/app/collection/uscode/2017/title52/subtitleIII/chapter301. 
- Statute links for 26 USC are pointing to https://api.fdsys.gov but need to point to https://www.govinfo.gov/app/collection/uscode/2017/title26/subtitleH
- Regulation links for 11 CFR are pointing to https://www.govinfo.gov/app/collection/cfr/2019/title11/chapterI

Some old bugs we had in the 2018 e-regs remain. See these issues for background: 
https://github.com/fecgov/fec-eregs/issues/393
https://github.com/fecgov/fec-eregs/issues/391

Let me know if I should test each section. I've clicked around various parts randomly and all seemed in order, and I checked through the regulations that were updated in 2018, and they are correct. The regulations that took effect in 2019 are not in this version, which was expected as we load the xml file that comes from the 2019 edition (which contains the rules as of 1/1/2019).

cc: @AmyKort @PaulClark2

**Comment by dorothyyeager** [comment]
GovInfo API link seems to be https://api.govinfo.gov/docs/.

**Comment by fec-jli** [comment]
2019 eregs has been loaded to `dev`, `stage`, `prod` successfully. All look good except existing `external link` eregs issue #393.[https://github.com/fecgov/fec-eregs/issues/393](https://github.com/fecgov/fec-eregs/issues/393)

**Comment by dorothyyeager** [comment]
Thanks @fec-jli!  Is this ticket ready to close?

**Comment by fec-jli** [comment]
@dorothyyeager  yes , It can be closed. Thanks

**Comment by dorothyyeager** [comment]
Closing this ticket as the e-regs for 2019 are now loaded. Thank you @fec-jli and @qqss88 for your work on this!
