### ISSUE TITLE
(Investigation) depended libraries not compatible 

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-eregs#447]
See the below diagram, we can see fec-reges repo depends on a couple of libraries: 
[Regulations Site](https://github.com/eregs/regulations-site), 
[Regulations Core](https://github.com/eregs/regulations-core),
[Regulations Parser](https://github.com/eregs/regulations-parser)

Currently, we face a couple of un-compatible issues:
### 1)The biggest issue is Regulations Parser 
Regulations Parser supports Python 3.5.
(1)Before May 29 2018, we can use Regulations Parser to load regulations locally.
The Python virtual env is 3.6.5 on local.

(2)After 05/29/2018, we have merged 11 PRs in, we didn't test parser during merging new PR. now, we get error when using Regulations Parser locally.The Python virtual env is still 3.6.5 on local.

(3)But, we can run Regulations Parser to load regulation locally on Python 3.6.1 successfully. we have uploaded 2019 regulations to dev,stage,prod fec-eregs-db and fixed duplicated 2018 and 2019 data, see issue: [https://github.com/fecgov/fec-eregs/issues/443](https://github.com/fecgov/fec-eregs/issues/443)

(4)We have ever tried to setup docker to run Parser locally. can parse data to folder but can not access outside container api . see issue: [https://github.com/fecgov/fec-eregs/issues/430](https://github.com/fecgov/fec-eregs/issues/430)

### 2)The second issue is Regulations Site
currently, it supports node 6.9.2.
and we need update menu. see issue: [https://github.com/fecgov/fec-eregs/issues/434](https://github.com/fecgov/fec-eregs/issues/434)

![eRegs Application Flow Char](https://user-images.githubusercontent.com/24395751/58996345-c1214180-87c5-11e9-89e6-dfd1d2ee771d.jpg)

**Comment by pkfec** [comment]
Eregs and Parser are now running on python 3.7.X in PR https://github.com/fecgov/fec-eregs/pull/647.
This is no longer an issue.
