### ISSUE TITLE
Audit Python and package versions

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-eregs#450]
**Summary**
As a developer, I would like to know:
* if there are backwards incompatibilities between package versions in use compared to most-recently available package versions
* the dependency tree for such packages (how do these packages affect other packages we use?)

**Why this matters**
Security compliance effort: 
* implementing required package upgrades may be simpler if packages in use are mostly current relative to those available
* potentially avoid needing to upgrade through several major versions of a package to get to necessary version, where each version may contain backwards incompatibility
* This concern applies also to the dependent package(s) which may need to be upgraded along with the target package (the dependent package(s) may need to go through several major versions)

**Potential benefits**
* possibly stay ahead of vulnerabilities in some cases, e.g., the very old package update case
* lower instantaneous effort for security compliance (but will benefit from disciplined ongoing/routine maintenance to avoid large jumps in package versions)
* An audit may allow for explicit decisions on which packages should be upgraded and which can safely be ignored with a plan developed accordingly

**Files to audit in `fec-eregs`**
- [ ] `requirements.txt`
- [ ] `requirements_dev.txt`
- [ ] `requirements_test.txt`
- [ ] `runtime.txt` (Python version)

**Comment by jason-upchurch** [comment]
|     package     |      location       |    current | newest | has_bkwrd_incompatible |
|  ---  |  ---  |  ---  |  ---  | --- |
| [`python`](https://docs.python.org/3/whatsnew/3.7.html)  |  `circleci` container/ `runtime.txt`|  3.6.3  |  3.7.4  | true  |

**Comment by pkfec** [comment]
Vulnerable packages are audited during weekly log process using SNYK tool. New Issues to handle package upgrades are submitted based on the severity.  Eregs parsing requirements are monitored/fixed on monthly basis.
