### ISSUE TITLE
Create new redundant RDS service, switch over before February 25

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-eregs#470]
We shouldn't be using the `shared-psql` database for production data. Cloud.gov is taking it down for at least an hour on Feb 25: https://cloudgov.statuspage.io/incidents/5f2tcw4gs10s

**Steps**
- [x] Test this in `dev` first
- [x] Create new  `medium-psql-redundant`  service, name it `fec-eregs-db-2` or something more helpful. 
```
cf create-service aws-rds medium-psql-redundant fec-eregs-db-2
```
- [x] Load backup into new DB - launch a headless app from API to bind to this service for creds? We don't want to bind `eregs` app until the data is loaded, or it will break. Trying to get an app bound to the new service that won't break, I figure a headless app would be best. We need to bind an app to the service to get creds (see backup wiki below)
- Go to slack #bots channel for info on eregs backup location
- For reference, backup/restore wiki https://github.com/fecgov/fec-cms/wiki/Backup-or-Restore-Wagtail-PostgreSQL-database-in-dev,-staging,-or-production
- [x] Bind eregs app to new service (update manifests)
- [x] Create doc in eregs wiki : [https://github.com/fecgov/fec-eregs/wiki/How-to-switch-shared-pqsl-service-to-medium-psql-redundant](https://github.com/fecgov/fec-eregs/wiki/How-to-switch-shared-pqsl-service-to-medium-psql-redundant)
- [x] Test app
- [x] Create ticket to add `medium-psql-redundant` services in `dev`  #475 
- [x] Test renaming the services?
- [x] Repeat in stage and prod
- [x] Create ticket to remove `shared-psql` service in `prod`  and `stage` #474 
- [x] DB team has updated Postgres client version to 11.5 and take backup daily.

**Completion criteria**
- [x] Use `medium-psql-redundant` RDS service in `prod`
- [x] Switch over before February 25 without downtime

**Comment by fec-jli** [comment]
follow up Issue: Remove old fec-eregs-db(shared-pqsl) service on stage and prod
[https://github.com/fecgov/fec-eregs/issues/474](https://github.com/fecgov/fec-eregs/issues/474)

**Comment by rjayasekera** [comment]
After the cloud.gov upgrade their version of Postgres to 11.5 we are unable to make daily local backups of eregs, since our local Postgres version is 9.6.  Since now we are using *medium-psql-redundant* do we still need to make daily backups?  cc @patphongs @lbeaufort 

pg_dump: server version: 11.5; pg_dump version: 9.6.17
pg_dump: aborting because of server version mismatch

**Comment by lbeaufort** [comment]
>After the cloud.gov upgrade their version of Postgres to 11.5 we are unable to make daily local backups of eregs, since our local Postgres version is 9.6. Since now we are using medium-psql-redundant do we still need to make daily backups? cc @patphongs @lbeaufort

@rjayasekera according to the cloud.gov docs, the `-redundant` RDS service is backed up by cloud.gov. https://cloud.gov/docs/services/relational-database/ How do we handle CMS backups? They are using the same service.

**Comment by fec-jli** [comment]
another followup ticket: 
Create a fec-eregs-db-rdn service on dev consistent with stage and prod space
[https://github.com/fecgov/fec-eregs/issues/475](https://github.com/fecgov/fec-eregs/issues/475)

**Comment by fec-jli** [comment]
All done. closed.
