### ISSUE TITLE
Remove old fec-eregs-db(shared-psql) service on stage and prod.

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-eregs#474]
Resolve issue: [https://github.com/fecgov/fec-eregs/issues/470](https://github.com/fecgov/fec-eregs/issues/470)
Ref PR : [https://github.com/fecgov/fec-eregs/pull/472](https://github.com/fecgov/fec-eregs/pull/472)

1) we already bind eregs app to new fec-eregs-db-rdn (medium-psql-redundant) on stage and prod.
2) As Paul approve, medium-psql-redundant only cost 0.23/month, so we will keep all 3 spaces (dev,stage,prod) to use medium-psql-redundant.
3) Note: cloud.gov already upgrade psql from 9.6 to 11.5 on 02/24/2020. so pg_dump and pg_restore won't work, need upgrade psql client version to match server version (11.5). Insert/select/update not affected. we don't have backup of fec-eregs-db-rdn anymore. we may find other to backup.

- [ ] Remove old fec-eregs-db(shared-pqsl) service after one week?

**Comment by pkfec** [comment]
@fec-jli Do you have any update on this ticket?

**Comment by fec-jli** [comment]
old instance  fec-eregs-db has been removed from prod and stage spaces. closed
