### ISSUE TITLE
Create a fec-eregs-db-rdn service  on dev consistent with stage and prod space

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-eregs#475]
Resolve issue: [https://github.com/fecgov/fec-eregs/issues/470](https://github.com/fecgov/fec-eregs/issues/470)
Ref PR : [https://github.com/fecgov/fec-eregs/pull/472](https://github.com/fecgov/fec-eregs/pull/472)

1) As Paul approve, medium-psql-redundant only cost 0.23/month, so we decide to keep all 3 spaces (dev,stage,prod) to use medium-psql-redundant.
2) Note: cloud.gov already upgrade psql from 9.6 to 11.5 on 02/24/2020. so pg_dump and pg_restore won't work, need upgrade psql client version to match server version (11.5). Insert/select/update not affected. we don't have backup of fec-eregs-db-rdn anymore. we may find other to backup.

- [x] Create a service call: fec-eregs-db-rdn and restore data
- [x] remove the old fec-eregs-db and fec-eregs-db-2 service

**Comment by pkfec** [comment]
@fec-jli PR #479 is merged. Is it OK to close this issue?

**Comment by fec-jli** [comment]
1)new db instance: fec-eregs-db-rdn has been created. the data loaded, bound app **eregs**.
2)remove all the useless db instances
3)update wiki, how to install postgresql 11.7.1 and run pg_dump/pg_restore locally.
[instance](https://github.com/fecgov/fec-eregs/wiki/How-to-switch-shared-pqsl-service-to-medium-psql-redundant)
