### ISSUE TITLE
On mobile, TOC remains open on top of content

### ISSUE THREAD

**Issue by ix4** [fecgov/fec-eregs#476]
Hi y'all. On [fec.gov/regulations](https://www.fec.gov/regulations/) while using a mobile browser (Chrome for Android in my case), once you select a specific regulation, the table of contents (not the main menu) remains open covering the content and is not dismissible.
![Capture+_2020-02-26-17-04-51](https://user-images.githubusercontent.com/38112035/75393111-6253a900-58bb-11ea-9467-4a58027c27b3.png)

**Comment by johnnyporkchops** [comment]
Fixed in https://github.com/fecgov/fec-eregs/pull/651
