### ISSUE TITLE
[Synk: Medium Severity] untrusted data in parso (Due: June 30, 2020)

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-eregs#492]
### Summary
Issues with no direct upgrade or patch:
  ✗ Deserialization of Untrusted Data [Medium Severity][https://snyk.io/vuln/SNYK-PYTHON-PARSO-174930] in parso@0.7.0
    introduced by parso@0.7.0 and 4 other path(s)
  No upgrade or patch available

**Completion criteria:**
- [ ] Check to see if there's a remediation path for this, or if this is still an issue for us
- [ ] Consider/document alternatives or workaround to solve this security issue and do that thing

**Comment by pkfec** [comment]
on my local ran `snyk test` on the latest eregs/develop branch and Parso is no longer a KNOWN vulnerability on eregs. Hence closing this issue.
