### ISSUE TITLE
Upgrade local eRegs DB to use Postgres 11

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-eregs#499]
### Summary

**What we're after:**
_The eRegs postgres databases in our cloud environment is now using postgress version 11. We need to make sure our local environment is running the same version, especially for those team members working on parsing eregs._

### Related issues

- https://github.com/fecgov/openFEC/issues/4332
- https://github.com/fecgov/fec-cms/issues/3757

### Completion criteria

- [x] Local eRegs database is running using Postgres V11

### Tech steps or considerations

- [x] Try running both Postgres V11 and Postgres V10.7 locally
- [x] Run local eRegs database using Postgres V11

**Comment by pkfec** [comment]
Steps to install posgres11 on local via homebrew:

install pg11 run -  `brew install postgresql@11`
export the postgresql v11 path to bash_profile - echo 'export PATH="/usr/local/opt/postgresql@11/bin:$PATH"' >> /Users/pkasireddy/.bash_profile
start the pg11 service  in background run - `brew services start postgresql@11`
check if pg11 service is UP and running - `brew services list`
choose which pg you want on your local: brew  services stop postgresql@10

<img width="1173" alt="Screen Shot 2020-06-24 at 8 52 23 AM" src="https://user-images.githubusercontent.com/11650355/85559801-0c3c0b80-b5f8-11ea-9701-2cab7569b584.png">

check pg11 service is UP and running: brew services list or restart pg11 service : brew services start postgresql@11
<img width="1138" alt="Screen Shot 2020-06-24 at 8 47 57 AM" src="https://user-images.githubusercontent.com/11650355/85559177-7a340300-b5f7-11ea-9d22-9953c857957f.png">


## To test/parse eregs on local pg11 DB: 
on eregs repo, `activate python 3.6.1` virtual environment: `pyenv activate eregs361`
<img width="870" alt="Screen Shot 2020-06-24 at 8 27 38 AM" src="https://user-images.githubusercontent.com/11650355/85556182-9aae8e00-b5f4-11ea-86bc-a6ad759653b0.png">

create a test db  run -  `createdb eregs-test`
<img width="1102" alt="Screen Shot 2020-06-24 at 8 26 31 AM" src="https://user-images.githubusercontent.com/11650355/85556062-7d79bf80-b5f4-11ea-863e-277962d7e866.png">


confirm the eregs-test db is of PG v11 - `psql postgres` :
<img width="1060" alt="Screen Shot 2020-06-24 at 8 25 59 AM" src="https://user-images.githubusercontent.com/11650355/85555912-5b803d00-b5f4-11ea-80d8-114c68e73414.png">

parser regs on local: 
<img width="1280" alt="Screen Shot 2020-06-24 at 12 08 36 PM" src="https://user-images.githubusercontent.com/11650355/85592041-d016a400-b613-11ea-9b32-d8c171c779b1.png">

Use a tool (pgadmin) or psql to connect to the test eregs db:  

Verify that the test eregs db PG v11.8. 
- SELECT version(); 
Also check all 45 regs parsed by running the following script
- SELECT  count(*)
FROM public.regcore_notice;

**Comment by pkfec** [comment]
On cloud.gov eregs shared DB version is PG 11. As mentioned in the ticket,  I have setup PG10 and PG11 on my local env and parse regs on my local. No issues.
