### ISSUE TITLE
Hitting the app directly gets 500 server error

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-eregs#500]
https://fec-prod-eregs.app.cloud.gov/

<img width="393" alt="Screen Shot 2020-05-15 at 11 44 57 AM" src="https://user-images.githubusercontent.com/31420082/82069599-885e3d80-96a1-11ea-9c52-79573adaab95.png">

It looks like this has been an issue for a while, but the app itself shouldn't just 500.

**Comment by patphongs** [comment]
Moved to PI 14

**Comment by pkfec** [comment]
I figured out for eregs why  https://fec-dev-eregs.app.cloud.gov/  throws an **Internal Server Error**. We been using the wrong eregs app URL to access the regulations. Path defined inside the proxy app settings for regulations.
See here -  https://github.com/fecgov/fec-proxy/blob/master/manifest_dev.yml#L16

Here is the correct URL to access regulations (eregs app):

- https://fec-dev-eregs.app.cloud.gov/regulations/
- https://fec-stage-eregs.app.cloud.gov/regulations/
- https://fec-prod-eregs.app.cloud.gov/regulations/

**Comment by pkfec** [comment]
No action required. We can close this issue.

**Comment by lbeaufort** [comment]
@pkfec if the intention is to redirect to https://fec-prod-eregs.app.cloud.gov/regulations/, we should add the redirect and not throw a 500 server error. I'd like to keep this open.

**Comment by pkfec** [comment]
@lbeaufort redirect should happen in proxy or eregs app?

**Comment by lbeaufort** [comment]
The app itself should redirect, because if we put the redirect in the proxy it will only work if a user accesses the app through the proxy.

**Comment by pkfec** [comment]
If we just add a redirect just at the app level, then the proxy URL will still thrown error. We may consider adding redirect at the proxy level too?

**Comment by lbeaufort** [comment]
@pkfec I'm not sure I understand the symptoms of a proxy issue, but if there's a problem there it seems like a good idea to fix that too. Maybe it would be easiest to hop on a call to discuss, if that works for you?

**Comment by pkfec** [comment]
Found some previous eregs issues that related to 500 errors :  https://github.com/fecgov/fec-eregs/issues/214

**Comment by pkfec** [comment]
After the 13.9 release (20201222), the URL https://fec-prod-eregs.app.cloud.gov/ now redirects to www.fec.gov.  Closing this issue.
