### ISSUE TITLE
Load the 2020 11 CFR into e-regs

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-eregs#502]
### What we are after
Making sure the newest version (2020)  of 11 CFR is parsed into e-regs

GPO links to different formats: https://www.govinfo.gov/app/details/CFR-2020-title11-vol1/

@dorothyyeager Put in changes in for the new regs so we know what to look for. - **DONE BELOW**

### Changed regulations: (in many of these cases, the change is to remove a reference to the Secretary of the Senate)

- 11 CFR 100.5 - Section (e)(3) revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=2
- 11 CFR 100.19 - Introductory text, section (a) and section (e) revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=2
- 11 CFR 101.1 - cross-references to 11 CFR part 105 removed and, where appropriate, the words ‘‘with the Commission’’ inserted - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=3
- 11 CFR 102.1 - sections (a) and (d) revised; cross-references to 11 CFR part 105 removed and, where appropriate, the words ‘‘with the Commission’’ inserted - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=3
- 11 CFR 102.2 - Heading and section (a)(1) changed - see https://sers.fec.gov/fosers/showpdf.htm?docid=408293.
- 11 CFR 102.3 - section (a)(1) revised: cross-references to 11 CFR part 105 removed and, where appropriate, the words ‘‘with the Commission’’ inserted - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=3
- 11 CFR 104.3 - Revised in two different rulemakings: 
--Section (b)(3)(vii)(B) revised: See https://sers.fec.gov/fosers/showpdf.htm?docid=401326#page=6
--Old section (b)(3)(vii)(C) moved to (b)(3)(vii)(D) with revisions - See https://sers.fec.gov/fosers/showpdf.htm?docid=401326#page=6
--Added new paragraph (b)(3)(vii)(C) - See https://sers.fec.gov/fosers/showpdf.htm?docid=401326#page=6
-- section (e)(5) revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=3
- 11 CFR 104.4 - Revised extensively in two different rulemakings: 
-- In section (b), remove ‘‘FEC Form 3X’’ everywhere it appears and add in its place the words ‘‘the
applicable FEC Form’’.
-- Revised paragraph (f). See https://sers.fec.gov/fosers/showpdf.htm?docid=401326
--Old paragraph (e)(2) removed, Old paragraph (e)(3) becomes paragraph (e)(2) but with revisions, old paragraph (e)(4) becomes paragraph (e)(3) with revisions. See https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=3
- 11 CFR 104.5 - section (f) revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=3 (last thing on the page)
- 11 CFR 104.14 - section (c) revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=4
- 11 CFR 104.18 - sections (a)(1) and (b) revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=4
- 11 CFR 104.20 - See https://sers.fec.gov/fosers/showpdf.htm?docid=401326#page=6 for these changes:
--Sections (c)(5) and (6) revised
-- Old sections (c)(7) through (9) renumbered as paragraphs (c)(8) through (10).
-- Added new paragraph (c)(7). 
- 11 CFR 104.22 - section (d) revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=4
- 11 CFR 105.1 revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=4
- 11 CFR 105.2, 105.3, 105.4 and 105.5 - These sections are removed and reserved. See the paragraph about Part 105 on https://sers.fec.gov/fosers/showpdf.htm?docid=402849 for an explanation. (See https://www.fec.gov/regulations/114-14/2019-annual-114#114-14 for an example of what a removed and reserved section looks like in e-regs.)
- 11 CFR 108.8 revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=4
- 11 CFR 109.10(e)(1)(iv) - see https://sers.fec.gov/fosers/showpdf.htm?docid=401326#page=7 (See top left of page)
- 11 CFR 110.6 sections (c)(1)(i) and (ii) revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=4
- 11 CFR 114.6 sections (d)(3)(i) and (d)(5) revised - see https://sers.fec.gov/fosers/showpdf.htm?docid=402849#page=4

### Completion criteria
- [x] Regs loaded onto dev
- [x] Regs loaded onto stage
- [ ] New regulations are loaded to the live website (Regs loaded onto prod)

### Tech considerations 
--Right now @jason-upchurch is the only one who has the parser working on his local
- [x] Reload the regulations in dev and stage
- [x] Test in dev and stage with content team
- [ ] Reload regulations in prod 
- [ ] Have team verify the regulations are updated in production

**Comment by dorothyyeager** [comment]
I've updated ticket with the regs that changed in the 2020 11 CFR. Most (not all) of the changes related to removing references to the Secretary of the Senate. So the list may look more scary than it really is. @jason-upchurch Please feel free to add me as a reviewer/tester if you want to doublecheck that we got all the revisions in.

**Comment by jason-upchurch** [comment]
2020 regs not completely parsing locally, so working on debugging. Verified with @pkfec and @fec-jli.

**Comment by jason-upchurch** [comment]
@dorothyyeager I've made some headway in parsing the regs, but I am getting this "Purpose and scope" (section 1.1) showing up. We don't currently show it (we start with 1.2 for some reason). Just wondering if you knew whether or not it was okay to have it.

<img width="1022" alt="Screen Shot 2020-06-04 at 9 23 45 AM" src="https://user-images.githubusercontent.com/49287206/83762860-02049e00-a646-11ea-8369-fc4bda078b80.png">

**Comment by jason-upchurch** [comment]
Actively working on debugging the `regparser`and demo'd parsing about 30 of the regulations for 2020 (some misformatted). Expect this to move to Sprint 12.6.

**Comment by jason-upchurch** [comment]
team call today at 1:00 pm to go over next steps now that regs are loaded locally.

**Comment by jason-upchurch** [comment]
@dorothyyeager the 2020 regs are loaded on dev here: 
https://fec-dev-eregs.app.cloud.gov/regulations/

**Comment by jason-upchurch** [comment]
Once regs are verified on `dev`, need to load onto `stage` and then `prod`

**Comment by dorothyyeager** [comment]
@jason-upchurch Left you a comment on the PR about the regs on dev. There's a few things to fix.

**Comment by dorothyyeager** [comment]
@jason-upchurch Tested on stage. The things I caught on dev were fixed (I left a similar comment in the PR) and it looks good as far as the content team goes. Thank you for your work on this.
