### ISSUE TITLE
decide on path forward for eregs

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-eregs#513]
### Summary
the parsing and front-end functionalities of `fec-eregs` have become out of sync. e.g., the python version for successful parsing has been tested on 3.6.1, but the front-end/deploy/build seems to require later python versions. What is our mid-to-long term plan for delivering and maintaining fec-eregs?

### Technical considerations
- [ ] fec-eregs works right now. Unfortunately, the "back-end" and "front-end" functionalities of fec-eregs is tightly coupled and the two functions cannot currently coexist in the same environment, i.e., pyenv. We could decouple these into two separate repos for easier and compartmentalized maintenance
- [ ] do we have bigger plans for eregs? e.g., eCFR (this will _also_ require developer time to implement and maintain)

**Comment by pkfec** [comment]
Eregs and Parser are now running on python 3.7.X. https://github.com/fecgov/fec-eregs/pull/647
