### ISSUE TITLE
Delete old eregs services

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-eregs#524]
These are old eregs services that need to be cleaned up and deleted:

- **Prod:** fec-eregs-db-rdn-2019
- **Stage:** fec-eregs-db-rdn-2019 and fec-eregs-db-rdn-old
- **Dev:** fec-eregs-db-rdn-2019  

**Completion criteria:**
- [ ] The above listed services are deleted

**Comment by lbeaufort** [comment]
```
  cf target -s dev
  cf services
  cf delete-service fec-eregs-db-rdn-2019
  cf target -s stage
  cf delete-service fec-eregs-db-rdn-2019
  cf delete-service fec-eregs-db-rdn-old
  cf target -s prod
  cf delete-service fec-eregs-db-rdn-2019
```
