### ISSUE TITLE
Suggest linking to to government eCFR site instead of commercial eCFR site

### ISSUE THREAD

**Issue by brittag** [fecgov/fec-eregs#532]
**Suggestion:**

On https://www.fec.gov/legal-resources/regulations/ at right under "Other Formats", there's a link to "eCFR" that goes to https://gov.ecfr.io/cgi-bin/text-idx?SID=de9b9ecf6ecae8b93dcb648941de180c&mc=true&tpl=/ecfrbrowse/Title11/11cfrv1_02.tpl

ecfr.io is a commercial site with ads on the bottom of the page. I would suggest instead linking to the official government e-CFR site: https://www.ecfr.gov/cgi-bin/text-idx?SID=b84fc4f2bb3ea03170784e83943daf19&mc=true&tpl=/ecfrbrowse/Title11/11tab_02.tpl

**Optional question:** 

Also, hi! I'm a former 18F employee who probably met some of you while I was working on cloud.gov, and I'm now a federal contractor working on a version of eRegs for the Center for Medicaid and CHIP Services. We're curious why your version of eRegs no longer has supplementary material in the sidebar - did you decide that wasn't the best way to maintain that kind of information for your readers?

**Comment by dorothyyeager** [comment]
Thanks @brittag - great catch and inadvertent error on our part. We have updated that link.

I'm looking into your question.

**Comment by PaulClark2** [comment]
@brittag See https://github.com/fecgov/fec-eregs/issues/203.   Thanks @dorothyyeager for finding this old issue.

**Comment by PaulClark2** [comment]
A little bit more, Timeline issue : https://github.com/fecgov/fec-eregs/issues/42. I'm having trouble finding other GitHub issues about the right side of eRegs. Please feel free to search the repository.

**Comment by dorothyyeager** [comment]
We'll close this now since we've updated the link to eCFR and linked issues answering the optional question.

**Comment by brittag** [comment]
Thank you, appreciate the explanation!

**Comment by brittag** [comment]
Also, as we reviewed FEC eRegs to learn from it, my coworker noticed that the "help" sidebar option still notes some of the removed features/buttons:

![Screen Shot 2020-10-15 at 2 08 42 PM](https://user-images.githubusercontent.com/391313/96186190-f082ab00-0eef-11eb-9061-b3bbdd357f5a.png)

I'm not sure we would have noticed this as ordinary readers, just sharing in case helpful for you.

**Comment by dorothyyeager** [comment]
Thanks @brittag - will open a separate ticket for this item.
