### ISSUE TITLE
e-regs right-sidebar still notes some of the removed features/buttons

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-eregs#533]
As reported by a user who was looking at how we set up e-regs and had asked about a feature we removed because it didn't work (see https://github.com/fecgov/fec-eregs/issues/532#issuecomment-709592737 and tickets linked in #532 for background):

> as we reviewed FEC eRegs to learn from it, my coworker noticed that the "help" sidebar option still notes some of the removed features/buttons

Screenshot provided by user:

![image](https://user-images.githubusercontent.com/24437369/96257331-2a9f8b80-0f88-11eb-987b-7ff49a68e92c.png)

**Comment by johnnyporkchops** [comment]
Closing in favor of Issue #639, PR: #651
