### ISSUE TITLE
Upgrade Node and NPM to latest

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-eregs#540]
## What we're after

Since Node 10 is coming up on its end-of-life, should we look at upgrading Node for e-regs?

## (semi-) Related tickets
- [CMS to Node 14 from Node 10](https://github.com/fecgov/fec-cms/issues/4152)
- [openFEC](https://github.com/fecgov/openFEC/issues/4676)
- [Pattern Library](https://github.com/fecgov/fec-pattern-library/issues/172)

**Completion Criteria:**
- [x] Upgrade NODE to LTS v14.13.0
- [x] Upgrade NPM to LTS v7.24.0
- [x] Parse 2021 regs on local

**Comment by pkfec** [comment]
Tried updated node/npm engine inside fec-eregs/package.json file.  Ran into node incompatible issue inside `regulations-site` repo. 

Error stack trace:
```

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'regulations-site@8.4.0',
npm WARN EBADENGINE   required: { node: '10.16.0' },
npm WARN EBADENGINE   current: { node: 'v14.13.0', npm: '7.24.0' }
npm WARN EBADENGINE }

```

**Comment by pkfec** [comment]
Unassigned and moved https://github.com/fecgov/fec-eregs/issues/540 to backlog.
Currently working on high priority  https://github.com/fecgov/openFEC/issues/4988.

**Comment by pkfec** [comment]
On eregs, 192 vulnerabilities are flagged in production environment. After upgrading Node/NPM packages, the vulnerabilities are down to 108.

```
Production:
found 192 vulnerabilities (13 low, 55 moderate, 111 high, 13 critical

```
```
feature/540-upgrade-node-npm branch:
found 108 vulnerabilities (6 low, 52 moderate, 44 high, 6 critical)
```

**Comment by pkfec** [comment]
> Tried updated node/npm engine inside fec-eregs/package.json file. Ran into node incompatible issue inside `regulations-site` repo. Error stack trace:
> 
> ```
> 
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'regulations-site@8.4.0',
> npm WARN EBADENGINE   required: { node: '10.16.0' },
> npm WARN EBADENGINE   current: { node: 'v14.13.0', npm: '7.24.0' }
> npm WARN EBADENGINE }
> ```
> 
> Have to upgrade NODE in `regulation-site` repo here: https://github.com/fecgov/regulations-site/blob/master/regulations/static/config/package.json

Upgrade node/npm on regulations-site here:https://github.com/fecgov/regulations-site/blob/master/regulations/static/config/package.json#L18-L20
