### ISSUE TITLE
Deploy eregs application with new Procfile/rolling deployments

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-eregs#542]
**What we're after**
In order to change the deploy command mechanism for eregs from a manifest command to a Procfile, we'll need to delete the old app and push up a new one. This seems to be because some cloud foundry internals prevent changing the start command mechanism (manifest vs. Procfile) on an exting app. (Docs: https://docs.cloudfoundry.org/devguide/deploy-apps/start-restart-restage.html#first-time) 

As a developer deploying the release, I'm more comfortable with a zero-downtime approach because it's less stressful and error-prone. As a user, I don't want to experience downtime.

We can do this with a zero-downtime approach by deploying a `eregs-temp`, deleting the old app, pushing up a new app, and deleting the `eregs-demp` app.

**Dev space** (before 11/5)
- [x] Before 11/5: `cf target -s dev`
- [x] Before 11/5: Push up `eregs-temp` app by changing app name in manifest to `eregs-temp` and using `cf push eregs-temp -f manifest_dev.yml` without changing eregs URL
- [x] Before 11/5: Delete old `eregs` app
- [x] Before 11/5: Merge PR which will deploy new `eregs` app
- [x] Before 11/5: Delete `eregs-temp` app

**Stage space**
- [x] Before 11/5: `cf target -s stage`
- [x] Before 11/5: Push up `eregs-temp` app by changing app name in manifest to `eregs-temp` and using `cf push eregs-temp -f manifest_stage.yml` without changing eregs URL
- [x] Before 11/5: Delete old `eregs` app: `cf delete eregs`
- [X] Make sure app looks ok
- [x] 11/5: Cut release branch which will deploy new `eregs` app to `stage`
- [x] 11/5: Delete `eregs-temp` app
- [x] Make sure app looks ok: https://stage.fec.gov/regulations

**Production**
- [x] Before 11/10: `cf target -s prod` and be sure you're in the eregs directory
- [x] Before 11/10: Push up `eregs-temp` app by changing app name in manifest to `eregs-temp` and using `cf push eregs-temp -f manifest_prod.yml` without changing eregs URL
- [x] Before 11/10: Delete old `eregs` app: `cf delete eregs`
- [x] Make sure app looks ok
- [x] 11/10: Deploy release which will deploy new `eregs` app to `production`
- [x] 11/10:  Delete `eregs-temp` app
- [x] Make sure app looks ok

**Comment by jason-upchurch** [comment]
completed on 11/10/2020, closing
