### ISSUE TITLE
Load the 2021 11 CFR into e-regs

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-eregs#580]
### What we are after
Making sure the newest version (2021)  of 11 CFR is parsed into e-regs

GPO links to different formats: will add link here when available 

Content Team will put in changes in for the new regs so we know what to look for.

### Completion criteria
- [x] Regs loaded onto dev
- [x] Regs loaded onto stage
- [x] New regulations are loaded to the live website (Regs loaded onto prod)

### Tech considerations 
- [x] Reload the regulations in dev and stage
- [x] Test in dev and stage with content team
- [x] Reload regulations in prod 
- [x] Have team verify the regulations are updated in production

**Comment by patphongs** [comment]
New 2021 regs are not out yet, moving to 14.6. https://www.govinfo.gov/bulkdata/CFR

**Comment by dorothyyeager** [comment]
Just checked, no 2021 regs yet, safe to move to 15.1.

**Comment by dorothyyeager** [comment]
Just checked, no 2021 regs online yet. Safe to move to 15.2

**Comment by pkfec** [comment]
Still waiting for 2021 regs to be published here -https://www.govinfo.gov/bulkdata/CFR

**Comment by patphongs** [comment]
2021 eregs bulk data has been released. This is now unblocked: https://www.govinfo.gov/bulkdata/CFR/2021/title-11

**Comment by pkfec** [comment]
> Content Team will put in changes in for the new regs so we know what to look for.

@dorothyyeager @kathycarothers Can you please post the changes for the new regs here when you get a chance?  So i can compare/verify the changes on `Dev` space first before i parse regs on other higher environments.

**Comment by dorothyyeager** [comment]
Here's the changes identified; all are in this FR notice
https://sers.fec.gov/fosers/showpdf.htm?docid=412651#page=2

111.24 - follow the instructions in the FR notice
111.43 - follow the table in the FR notice
111.44 - in paragraph (a)(1), remove ‘‘$146’’ and adding, in its
place, ‘‘$149’’

**Comment by dorothyyeager** [comment]
There's another rulemaking I want to check on that's mentioned in pending rulemakings as supposed to be corrected in 2021. I didn't see the change when I looked. I'll check into it with OGC and Brad and get back to you if there is another change to make.

**Comment by pkfec** [comment]
> Here's the changes identified; all are in this FR notice
> https://sers.fec.gov/fosers/showpdf.htm?docid=412651#page=2
> 
> 111.24 - follow the instructions in the FR notice
> 111.43 - follow the table in the FR notice
> 111.44 - in paragraph (a)(1), remove ‘‘$146’’ and adding, in its
> place, ‘‘$149’’

I parsed 2021 regs in my local env and verified that above mentioned changes showed on my local environment.

**Comment by pkfec** [comment]
Myself and @fec-jli tried loading 2021 regs onto stage env. Noticed that EREGS app PROXY URL (https://fec-stage-eregs.app.cloud.gov/regulations/ should redirect to https://stage.fec.gov/regulations/) is not redirect to the app.  
For the same reason, `cf run-task api --command "python manage.py load_regulations" --name load_all_regulations` task failed to reload regulations onto elasticsearch service.

@lbeaufort built the proxy-redirect app on stage and the URL seems to redirect to eregs app now.

**Comment by pkfec** [comment]
Completed loading 2021 regs onto stage space here: https://stage.fec.gov/regulations/

**Comment by pkfec** [comment]
2021 Regs loaded onto website https://www.fec.gov/regulations

**Comment by dorothyyeager** [comment]
@pkfec I compared what's on prod to the [2020 admin fines FR notice](https://sers.fec.gov/fosers/showpdf.htm?docid=412651. ) and all checked out perfectly. Those were the only regulations that changed in 2020.  The current admin fines rules didn't make the 2021 CFR cutoff, so we have a ticket to redirect these to the 2021 versions that will be deployed with the 15.5 release - https://github.com/fecgov/fec-proxy/issues/281

Long way of saying, you're all good from our end of it! Thanks for working on this!
