### ISSUE TITLE
[SNYK: HIGH] - django-debug-toolbar - SQL Injection (due 9/18/21)

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-eregs#615]
django-debug-toolbar is an A configurable set of panels that display various debug information about the current request/response.

Affected versions of this package are vulnerable to SQL Injection in the SQL Panel in Jazzband Django Debug Toolbar. It allows attackers to execute SQL statements by changing the raw_sql input field of the SQL explain, analyze, or select form.

**Remediation:**
Upgrade django-debug-toolbar to version 1.11.1, 2.2.1, 3.2.1 or higher.

More info: https://app.snyk.io/vuln/SNYK-PYTHON-DJANGODEBUGTOOLBAR-1246398

**Comment by pkfec** [comment]
Testing on local by removing  `django-debug_toolbar` package from requirements_dev.txt and requirements-parsing.txt
