### ISSUE TITLE
[Snyk: Medium] Access Restriction Bypass (03/08/2022)

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-eregs#638]
### Overview
Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.

Affected versions of this package are vulnerable to Access Restriction Bypass. HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths.

https://security.snyk.io/vuln/SNYK-PYTHON-DJANGO-2312875

### Detailed paths:
Introduced through: project@0.0.0 › django@2.2.24
Fix: Upgrade django to version 2.2.25 or 3.1.14 or 3.2.10 
Introduced through: project@0.0.0 › django-haystack@2.4.1 › django@2.2.24
Fix: Pin django to version 2.2.25 or 3.1.14 or 3.2.10

### Remediation:
Upgrade django to version 2.2.25 or 3.1.14 or 3.2.10 

### Completion criteria:
- [ ] Upgrade django to version 2.2.25 or 3.1.14 or 3.2.10 
- [ ]  Parser regulations on local

**Comment by JonellaCulmer** [comment]
No longer a vulnerability. We have upgraded to 3.2.10.
