### ISSUE TITLE
[Snyk: High] NULL Pointer Dereference Node-Sass (Due: 2/26/2022)

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-eregs#659]
node-sass is a Node.js bindings package for libsass.

Affected versions of this package are vulnerable to NULL Pointer Dereference in the function Sass::Functions::selector_append which could be leveraged by an attacker to cause a denial of service (application crash) or possibly have unspecified other impact. node-sass is affected by this vulnerability due to its bundled usage of libsass.

Vulnerable module: node-sass
Introduced through: node-sass@7.0.1

**Detailed paths**
Introduced through: node-sass@7.0.1

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/fec-eregs/issues/644. 

This is a duplicate ticket.
