### ISSUE TITLE
[February] eRegs parsing requirements

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-eregs#661]
Take a look at Snyk vulnerabilities for requirements-parsing.txt and upgrade relevant packages to maintain the parsing tool

**requirements-parsing.txt**: 2 High, 2 Medium, 2 Low
- [x] [Snyk: High] requests-cache Arbitrary Code Execution
- [ ] [Snyk: High] networkx Deserialization of Untrusted Data
- [x] [Snyk: Medium]: celery Stored Command Injection
- [x] [Snyk: Medium]: django Denial of Service (DoS)
- [x] [Snyk: Low]: django Directory Traversal
- [x] [Snyk: Low]: django Information Exposure

**Completion criteria:**
- [x] Check and document parsing requirements and upgrades in Snyk
- [x] Upgrade packages where necessary
- [x] Create a ticket to check for the month of March

**Comment by pkfec** [comment]
[Snyk: Medium]: celery Stored Command Injection is addressed in 
https://github.com/fecgov/fec-eregs/pull/665

**Comment by pkfec** [comment]
except `[Snyk: High] networkx Deserialization of Untrusted Data` all other vulnerable parsing requirement packages are upgraded in PR https://github.com/fecgov/fec-eregs/pull/671

**Comment by pkfec** [comment]
Networkx is very tricky. When upgraded Networkx to 2.6, eregs failed to parse. The latest i could upgrade Networkx is to 2.3 along decorator v4.4.2. Need more time to test. 

I will move the networkx package to [March] eregs parsing requirements issue.
