### ISSUE TITLE
[June 2022] eRegs parsing requirements

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-eregs#685]
Take a look at Snyk vulnerabilities for `requirements-parsing.txt` and upgrade relevant packages to maintain the parsing tool

**Related issue** #675

**Action Items**:
- [x] Check and document parsing requirements and upgrades in Snyk

**Completion criteria:**
- [x] Upgrade packages in requirements-parsing.txt
- [x] Setup and parse 2022 regulations on local environment
- [x] Create a ticket to check for the month of July

**Comment by cnlucas** [comment]
![Screen Shot 2022-06-01 at 3 56 34 PM](https://user-images.githubusercontent.com/66386084/171491843-afb4903a-774d-406a-a934-e17824bd1ded.png)

No vulnerabilities detected, July ticket created #689
