### ISSUE TITLE
psycopg2 install error on Monterey OS version 12.4

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-eregs#690]
### Summary

An error occurred within the CMS repo when trying to pip install `psycopg2==2.8.6` on Monterey version 12.4. Upgrading to `psycopg2==2.9.3` fixed the error.

**Error:**

```
ld: library not found for -lssl
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> psycopg2
```

### Related issue
- https://github.com/fecgov/fec-cms/issues/4916
- https://github.com/fecgov/fec-cms/issues/5293

### Completion criteria

- [ ] Research and document path forward for the 'psycopg2' package
- [ ] Document bugs when upgrading to `psycopg2==2.9.3`

### Tech steps or considerations

Test `psycopg2==2.9.3` on older OS versions:
- [ ] Monterey versions less than 12.4
- [ ] Big Sur
- [ ] Catalina
- [ ] Mojave
- [ ] Test deploy to dev

**Comment by pkfec** [comment]
On my MAC, I recently upgraded macOS Monterey to v12.4 and xcode to v13.4.1. I was able to setup/build/parse and run eregs app without running any psycopg2 errors on my local workspace. Here are the steps that i followed

Here are the steps i followed:

1. update macOS Monterey to v12.4 
2. update xcode to v13.4.1
3. run brew update and brew upgrade (Upgrade postgresql@13 13.6_1 -> 13.7)
4. followed  [eregs-wiki](https://github.com/fecgov/fec-eregs/wiki/Parse-regulations-on-local) and setup/build/run and parse 2021 regulations on my local workspace

No changes required on eregs repo. Hence closing this issue.
