### ISSUE TITLE
 [August 2022] eRegs parsing requirements

### ISSUE THREAD

**Issue by cnlucas** [fecgov/fec-eregs#699]
Take a look at Snyk vulnerabilities for `requirements-parsing.txt` and upgrade relevant packages to maintain the parsing tool

Run:
snyk test --file=requirements-parsing.txt --package-manager=pip

**Action Items**:
- [x] Check and document parsing requirements and upgrades in Snyk

**Completion criteria:**
- [ ] Upgrade packages in requirements-parsing.txt
- [ ] Setup and parse 2022 regulations on local environment
- [x] Create a ticket to check for the month of ~August~ September

**Comment by pkfec** [comment]
No vulnerabilities found for the month of August.
