### ISSUE TITLE
Load the 2022 11 CFR into e-regs

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-eregs#704]
### What we are after
Making sure the newest version (2022)  of 11 CFR is parsed into e-regs once it is available.

GPO links to different formats; Watch this page for 2022: https://www.govinfo.gov/bulkdata/CFR

Content Team will put in changes in for the new regs so we know what to look for.

### Changes to be made (to be filled in by content person)

Technical corrections (https://sers.fec.gov/fosers/showpdf.htm?docid=414978):

- [x] 1.2 - Change the definition of ‘‘Commission’’ to read "Commission means the Federal Election Commission, its Commissioners, and employees. The Commission is located at 1050 First Street NE, Washington, DC 20463. The
Commission’s website is www.fec.gov."

- [x] 104.2(b) - Add ‘‘https://www.fec.gov/help-candidatesand-committees/forms/ or at’’ before the
words ‘‘the street address identified’’

- [x] 110.1(b)(3)(ii)(C) - remove ‘‘116.11(b)’’ and add in its place ‘‘116.11(a)"

Admin fine updates - December 2021 https://sers.fec.gov/fosers/showpdf.htm?docid=415017

- [x] 111.24 - Update table to reflect what's in the [FR notice](https://sers.fec.gov/fosers/showpdf.htm?docid=415017#page=3)

- [x] 111.43(a) and (b) - Update table to reflect what's in the [FR notice](https://sers.fec.gov/fosers/showpdf.htm?docid=415017#page=3)

- [x] 111.43(c) - Change text to read: " If the respondent fails to file a required report and the Commission
cannot calculate the level of activity under paragraph (d) of this section, then the civil money penalty shall be $8,743."

- [x] 111.44(a)(1) - Change the amount of the penalty to be ‘‘$160’’.

### Completion criteria
- [x] Regs loaded onto dev
- [x] Regs loaded onto stage
- [x] New regulations are loaded to the live website (Regs loaded onto prod)

### Tech considerations 
- [x] Reload the regulations in dev and stage
- [x] Test in dev and stage with content team
- [x] Reload regulations in prod 
- [x] Have team verify the regulations are updated in production

**Comment by dorothyyeager** [comment]
@pkfec I've updated the list of regs to change.

**Comment by pkfec** [comment]
@dorothyyeager @kathycarothers: I have parsed 2022 regulations onto `Dev` space. Could you please test and confirm the changes appear  [here](https://dev.fec.gov/regulations/). Thanks for your help!

**Comment by kathycarothers** [comment]
@pkfec @dorothyyeager I noticed two things. 111.24 I don't see the chart.  and for 111.43 Table 1 and 2 the rows are out of sync. I believe we experienced the rows being out of order last time around too. The other regs look good.

**Comment by dorothyyeager** [comment]
@pkfec Here's what I caught. They are looking good. I did see the tables for 111.24

111.24(a)(2)(1) - should be $46,517
111.43(a) -in the $850,000 line, need to take out extra space between the $ and 18,280

**Comment by pkfec** [comment]
> @pkfec Here's what I caught. They are looking good. @kathycarothers No tables in 111.24, those are text edits. FR notice uses a table to show them.
> 
> 111.24(a)(2)(1) - should be $46,517 111.43(a) -in the $850,000 line, need to take out extra space between the $ and 18,280

@dorothyyeager Like we discussed,  [2022 11 CFR](https://www.govinfo.gov/content/pkg/CFR-2022-title11-vol1/pdf/CFR-2022-title11-vol1.pdf) --> 111.24(a)(2)(1) the amount is mentioned as $46,217.  Thanks for reaching out to OGC and reporting about this mismatch amount.

**Comment by pkfec** [comment]
2022 Regs parsed on Stage. Here is the [link](https://stage.fec.gov/regulations/) to the 2022 regulations on Stage environment

**Comment by pkfec** [comment]
@dorothyyeager @kathycarothers 2022 regulations are parsed on [Production](https://www.fec.gov/regulations/). 
Please test one last time to make sure the latest changes appear on the website regulations page.

**Comment by kathycarothers** [comment]
Looks good
