### ISSUE TITLE
[SNYK MEDIUM] botocore Race Condition (due by 10/27/2023)

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-eregs#780]
### **Overview**
Affected versions of this package are vulnerable to Race Condition related to assuming a role for the first time.

### 
**Introduced through**
Introduced through: project@0.0.0 › boto3@1.5.13 › botocore@1.8.50

### **Fixed in**
botocore@1.9.12

### Completion criteria:
- [ ] Pin botocore to version 1.9.12 
- [ ] SNYK TEST no longer flags botocore as vulnerable package

Snyk: [CVSS 5.9](https://security.snyk.io/vuln/SNYK-PYTHON-BOTOCORE-5812631) - Medium Severity

**Comment by tmpayton** [comment]
Implemented with this PR https://github.com/fecgov/fec-eregs/pull/783
