### ISSUE TITLE
Load the 2023 CFR into e-regs

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-eregs#790]
### What we are after
Making sure the newest version (2023) of 11 CFR is parsed into e-regs once it is available.

GPO links to different formats;  https://www.govinfo.gov/bulkdata/CFR/2023/title-11

Content Team will put in changes in for the new regs so we know what to look for. Note this task has been done. 

### Changes to be made  
 
**Repayment of Candidate Loans**, [87 Fed. Reg. 54862 (September 8, 2022)](https://sers.fec.gov/fosers/showpdf.htm?docid=420045) Effective date: November 30, 2022 

Changes to make to 110.1:

- [x]  In paragraph (b)(3)(ii)(A),  add ‘‘and’’ after the semicolon at the end of the paragraph;
- [x]  In paragraph (b)(3)(ii)(B), remove ‘‘; and’’ and adding a period in its place; and
- [x]  Remove paragraph (b)(3)(ii)(C)

Changes to make to Part 116:

- [x] Remove 116.11 and 116.12.

**Reporting Independent Expenditures**, [87 Fed. Reg. 35863 (June 14, 2022)](https://sers.fec.gov/fosers/showpdf.htm?docid=419100) Effective date: September 30, 2022 

Changes to make to 109.10:

- [x] Remove and reserve paragraph (e)(1)(vi) 
- [x] - Add a note to paragraph (e)(1). Note should read, "**Note to § 109.10(e)(1):** On August 3, 2018, the United States District Court for the District of Columbia vacated 11 CFR 109.10(e)(1)(vi). _CREW v. FEC_, 316 F. Supp. 3d 349 (Aug. 3, 2018), _aff’d_, 971 F.3d 340 (D.C. Cir. 2020). Section 30104(c) of title 52 of the U.S. Code and the remaining provisions of 11 CFR 109.10 remain in force."

### Completion criteria
Load eregs instructions: https://github.com/fecgov/fec-eregs/blob/develop/load_regs/README.md
- [x]  Regs loaded onto dev
- [x]  Regs loaded onto stage
- [x]  New regulations are loaded to the live website (Regs loaded onto prod)

### Tech considerations

-  Reload the regulations in dev and stage
-  Test in dev and stage with content team
-  Reload regulations in prod
-  Have team verify the regulations are updated in production

### Related issue:
Load the 2022 11 CFR into e-regs #704

**Comment by pkfec** [comment]
Loaded 2023 ERegs onto Dev website.

**Comment by pkfec** [comment]
2023 Eregulations are loaded onto Stage and Prod website. Hence closing this issue
