### ISSUE TITLE
 [December 2023] eRegs parsing requirements

### ISSUE THREAD

**Issue by tmpayton** [fecgov/fec-eregs#816]
Take a look at Snyk vulnerabilities for `requirements-parsing.txt` and upgrade relevant packages to maintain the parsing tool

**Reference ticket:** https://github.com/fecgov/fec-eregs/issues/812

**Action Items** :
- [x] Check and document parsing requirements and upgrades in Snyk
    -  Run: snyk test --file=requirements-parsing.txt --package-manager=pip

**Completion criteria:**
- [x] Upgrade vulnerable packages in requirements-parsing.txt
- [x] Setup and parse 2023 regulations on local environment
    - Parse eregs locally: https://github.com/fecgov/fec-eregs/wiki/Parse-regulations-on-local
- [x] Create a new ticket to check for the month of January 2024

**Comment by pkfec** [comment]
```
Issues with no direct upgrade or patch:
  ✗ Denial of Service (DoS) [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-6050294] in cryptography@41.0.6
    introduced by cryptography@41.0.6 and 1 other path(s)
  No upgrade or patch available
  ✗ Information Exposure [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-6126975] in cryptography@41.0.6
    introduced by cryptography@41.0.6 and 1 other path(s)
  No upgrade or patch available
```
