### ISSUE TITLE
Research eCFR API and the capabilities

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-eregs#826]
### Summary

**What we're after:**
Need to research the following areas in eCFR:

- [x]  Text search
- [x]  Search by citation
- [x]  Pulling in the most up-to-date list of citations
- [x]  Highlighting
- [x]  Comparison (something our regulations app does not currently have, but would be nice to implement if we can)
- [x]  Navigation of Title 11 via the API

**eCFR API documentation:** https://www.ecfr.gov/developers/documentation/api/v1#/Search%20Service/get_api_search_v1_results

### Related issues
-  https://github.com/fecgov/fec-eregs/issues/589
- https://github.com/fecgov/fec-cms/issues/6089
- https://github.com/fecgov/fec-proxy/issues/393

### Completion criteria
- [x] Capabilities are documented in this ticket and plan has been determined for next steps
        - See findings in [comment below](https://github.com/fecgov/fec-eregs/issues/826#issuecomment-1939134277)

**Comment by johnnyporkchops** [comment]
### Navigation:
The `structure` endpoint returns the nested structure of Title 11 for a given date: 
**/api/versioner/v1/structure:**

- A search in  swaggar docs results in a `download file` link where you can download a hash-named file.
- A direct call to the endpoint in a browser automatically downloads the title-11.json file.
          - https://www.ecfr.gov/api/versioner/v1/structure/2024-02-01/title-11.json
- A fetch call in an application, you can call the endpoint and capture the data to the promise  without downloading the         

### Text search
The `results` endpoint returns works for text searches
**/api/search/v1/results**
- Exampe text search  for “firewall”:
        - https://www.ecfr.gov/api/search/v1/results?query=firewall&agency_slugs%5B%5D=federal-election-commission&per_page=20&page=1&order=relevance&paginate_by=results
        - Returns expected reg 109.21 .

### Highligthting:
The queiried string in the text search above is wrapped in a strong tag in the excerpt, which gives up potential to highlight.

### Content:
The `full` endpoint returns raw XML (without linked regs):
**/api/versioner/v1/full**

- Example API call for XML for  6.103:
        - https://www.ecfr.gov/api/versioner/v1/full/2024-02-01/title-11.xml?section=6.103

- Also eCFR “renderer” links can return xml with links added (This endpoint is not in swaggar docs):
Exampe: https://www.ecfr.gov/api/renderer/v1/content/enhanced/2024-02-08/title-11?chapter=I&part=6&section=6.103

- To navigate to this html,  click on “developer tools” button on the left sidebar while in an eCFR section.

### Citations:
TBD. Need more research to understand how citattion might be found. Not readily apparent from looking at API docs.

### Comparison
- Many of the endpoints require(or allow as optional) a date to get data so this could be developed into an app using that parameter.
- For example, the `summary` endpoint has these fields which could be used for point-in-time comparison
**/api/search/v1/summary**
date
last_modified_after
last_modified_on_or_after
last_modified_before
last_modified_on_or_before
